#!/bin/bash
    
    while true
    do
    read -p "Przed rozpoczeciem pracy skryptu, nalezy manualnie, dowolnie, lecz poprawnie popartycjonowac dysk. Kontynuowac? [t/n] " tn
    case $yn in
        [Tt]* ) break;;
        [Nn]* ) exit && cfdisk;;
        * ) echo "Nieprawidlowa opcja";;
    esac
    done
pacstrap -K /mnt base linux linux-firmware
cp script /mnt/script
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt bash script
