#!/bin/bash

while true; do
    read -p "Czy przed uruchomieniem skryptu zamontowano niezbedne do instalacji partycje? " tn
    case $tn in
        [Tt]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Nieprawidlowa odpowiedz";;
    esac
done
pacstrap -K /mnt base linux linux-firmware
cp script /mnt/script
genfstab -U /mnt >> /mnt/etc/fstab
echo "Teraz nalezy uruchomic dalsza czesc skryptu, uzywajac komendy "bash script""
arch-chroot /mnt
