#!/bin/bash

# install
pacstrap -K /mnt base linux linux-firmware

# copy the second script
cp skrypt2 /mnt/skrypt2

# generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# change root
arch-chroot /mnt
chmod +x skrypt2
./skrypt2
